# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-navigation-extension}
  s.version = "2.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Phil Schilter", "Dirk Kelly"]
  s.date = %q{2010-11-28}
  s.description = %q{Navigation provides a way to generate navigation (with useful classes)}
  s.email = %q{dk@dirkkelly.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README"
  ]
  s.files = [
    "CHANGELOG",
    "LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "lib/navigation/tags/core.rb",
    "lib/navigation/tags/helpers.rb",
    "lib/radiant-navigation-extension.rb",
    "navigation_extension.rb"
  ]
  s.homepage = %q{http://github.com/dirkkelly/radiant-navigation-extension}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Navigation Generation for Radiant CMS}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

